### ISSUE TITLE
windowsta ios build 

### ISSUE THREAD

**Issue by yasintz** [burhanyilmaz/reactnative-forum#1]
mehaba windowsta iphone kullanarak ios buildi alabilirmiyiz

**Comment by enesfurkangenc** [comment]
@yasintazeoglu eğer ki bir ios cihazın varsa [expo](https://expo.io/) uygulamasıyla local bir sunucu yardımıyla ios platform buildi aldırabiliyor.

**Comment by yasintz** [comment]
Tesekkurler @enesfurkangenc

**Comment by burhanyilmaz** [comment]
@enesfurkangenc dediği gibi expo da yapabilirsin bunun dışında osx dışında hiç bir işletim sisteminde alamazsın.
