### ISSUE TITLE
FlatList renderItem'larının state'leri hakkında.

### ISSUE THREAD

**Issue by berksafran** [burhanyilmaz/reactnative-forum#2]
Merhaba,

Stackoverflow'da açtığım şöyle bir problem var. 

https://stackoverflow.com/questions/58364264/does-state-of-flatlists-renderitem-reset-when-extradata-work

Yardımcı olursanız sevinirim.

**Comment by burhanyilmaz** [comment]
@berksafran Merhaba,
issue yeni gordum. Link aktif degil sanırsam cozebildiniz mi?

**Comment by berksafran** [comment]
FlatList'lerin state'lerinin sıfırlanmasının en güzel ve sağlam yolu, `<FlatList>` componentini `unmount` edip, daha sonra tekrar `mount` etmek olduğunu deneyimledim. Muhtemelen hooks'lar ile de kalıcı bir çözüm bulunabilirdi ama şuan en mantıklı yolu bulduğumu düşünüyorum.
